---
name: "IMVDb"
guid: "e29621a5-fa9e-4330-982e-ef6e54c0cad2"
version: 4
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Get Music Video metadata from IMVDb"
description: >
  Get Music Video metadata from IMVDb

category: "Music"
artifacts:
  - "Jellyfin.Plugin.IMVDb.dll"
changelog: |-
  - 10.9 (#21) @crobibero

  ### Code or Repo Maintenance ###
  - Update link to Jellyfin website (#20) @methbkts

  ### Dependency updates ###
  - chore(deps): update dependency stylecop.analyzers to v1.2.0-beta.435 (#16) @renovate

  ### CI & build changes ###
  - fix: meta ci workflows (#14) @h1dden-da3m0n
