---
name: "IMVDb"
guid: "e29621a5-fa9e-4330-982e-ef6e54c0cad2"
version: "4"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Get Music Video metadata from IMVDb"
description: >
  Get Music Video metadata from IMVDb

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.IMVDb.dll"
changelog: |-

