---
name: "IMVDb"
guid: "e29621a5-fa9e-4330-982e-ef6e54c0cad2"
version: 5
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Get Music Video metadata from IMVDb"
description: >
  Get Music Video metadata from IMVDb

category: "Music"
artifacts:
  - "Jellyfin.Plugin.IMVDb.dll"
changelog: |-
  - Jellyfin 10.11 support (#29) @crobibero
  - Update settings page (#30) @thornbill

  ### Bug Fixes ###
  - Restore manual search for new items (#27) @abrain
