---
name: "IMVDb"
guid: "e29621a5-fa9e-4330-982e-ef6e54c0cad2"
version: 6
targetAbi: "10.11.5.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Get Music Video metadata from IMVDb"
description: >
  Get Music Video metadata from IMVDb

category: "Music"
artifacts:
  - "Jellyfin.Plugin.IMVDb.dll"
changelog: |-
  - Revert "Update dependency Microsoft.Extensions.Http to v10" (#33) @Shadowghost

  ### Dependency updates ###
  - Update dependency Microsoft.Extensions.Http to v10 (#31) @[renovate[bot]](https://github.com/apps/renovate)
